# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuoyarstudent',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
