# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0002_auto_20171107_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(null=True, to='shuoyar.Auther'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shuoyar.Publisher'),
        ),
    ]
