# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0002_shuoyarstudent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuoyarstudent',
            name='sid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shuoyarstudent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
