# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0003_auto_20171103_0016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shuoyarstudent',
            table='shuoyarStudentnew',
        ),
    ]
