# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0003_auto_20171115_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='shuoyar.Author'),
        ),
    ]
