# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0004_auto_20171115_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdn', models.IntegerField(null=True, unique=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shuoyar.Book_info'),
        ),
    ]
