# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuoyar', '0004_auto_20171104_2355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shuoyarstudent',
            table='Student',
        ),
    ]
